// <auto-generated />
namespace WinFormSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedtableshistoryandincidents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtableshistoryandincidents));
        
        string IMigrationMetadata.Id
        {
            get { return "202112071022014_added-tables-history-and-incidents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
